name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docker-compose
        run: docker-compose -f docker-compose.test.yml up -d --force-recreate
      - name: Check running containers
        run: docker ps -a
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm run start
